name: bdborme-empresas
proxy:
  appserver:
    - bdborme-empresas.lndo.site:8080
services:
  appserver:
    type: compose
    services:
      image: "python:3.8-slim-buster"
      command: /bin/sh -c "flask run --host=0.0.0.0 --port=8080 --debug"
      ports:
        - "8080:8080"
      volumes:
        - .:/app  # Monta el directorio actual en '/app' dentro del contenedor
      working_dir: /app  # Establece el directorio de trabajo dentro del contenedor
      environment:
        FLASK_APP: main.py
        FLASK_ENV: development
    build_as_root:
        - pip install -r /app/requirements.txt
    ssl: true
  mongo:
    type: mongo:4.2
    ports:
      - "27017:27017"
tooling:
  python:
    service: appserver
    description: Run Python commands
  pip:
    service: appserver
    description: Run Pip commands
  flask:
    service: appserver
    description: Run Flask commands
  mongo:
    service: mongo
    description: Run MongoDB commands