name: bd.borme-empresas
services:
  app:
    type: python:3.8
    command: flask run --host=0.0.0.0 --port=8080
    ports:
      - "8080:8080"
    volumes:
      - .:/bd.borme-empresas # Monta el directorio actual en '/app' dentro del contenedor
    working_dir: /bd.borme-empresas # Establece el directorio de trabajo dentro del contenedor
    via: pip
    environment:
      FLASK_APP: main.py
    ssl: false
    xdebug: false
    config:
      - DATABASE_URI=mongodb://mongo:27017/mydatabase
    tooling:
      - name: python
        service: app
      - name: pip
        service: app

  mongo:
    type: mongo:4.2
    ports:
      - "27017:27017"

tooling:
  python:
    service: app
    description: Run Python commands
  pipenv:
    service: app
    description: Run Pip commands
  mongo:
    service: mongo
    description: Run MongoDB commands
